<a href="https://colab.research.google.com/github/nomanabdullah04/MaChineLearning/blob/MachineLearning/RandomForestMachineLearAlgo(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**We are implement another problem for RFM for Regressor**

---

# ***Car price prediction***

In [153]:
#Import basic liberises
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [154]:
df=pd.read_csv('/content/sample_data/cardekho_dataset.csv')
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [156]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [157]:
print(df.duplicated().sum())

0

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [159]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

# **Feature Engineering**

In [160]:
##Getting all different types of feature
num_feature=[feature for feature in df.columns if df[feature].dtype!='O']
cat_feature=[feature for feature in df.columns if df[feature].dtype=='O']
discrite_feature=[feature for feature in num_feature if len(df[feature].unique())<25]
continous_feature=[feature for feature in num_feature if feature not in discrite_feature]
print(len(num_feature))
print(cat_feature)
print(discrite_feature)
print(continous_feature)

8
['car_name', 'brand', 'model', 'seller_type', 'fuel_type', 'transmission_type']
['vehicle_age', 'seats']
['Unnamed: 0', 'km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [161]:
##Remove Unnecessary Columns
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.drop(['car_name'],axis=1,inplace=True)
df.drop(['brand'],axis=1,inplace=True)
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [162]:
#Define idpendent and dependent feature
x=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [163]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

# ***Feature Encoding and Scaling***

In [164]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [165]:
#Create column Transformer with 3 types of transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler

# Define num_feature and cat_feature based on the state of x after label encoding 'model'
# and before conversion to csr_matrix.
# 'Unnamed: 0', 'model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats' were numeric.
# 'car_name', 'brand', 'seller_type', 'fuel_type', 'transmission_type' were categorical.
num_feature = ['model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']
cat_feature = ['seller_type', 'fuel_type', 'transmission_type']

print(num_feature)
print(cat_feature)
len(df['seller_type'].unique())

['model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']
['seller_type', 'fuel_type', 'transmission_type']

3

In [166]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
#Label encoding to the feature model
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x['model'] = label_encoder.fit_transform(x['model'])

In [167]:
numerical_transformer=StandardScaler()
categorical_transformer=OneHotEncoder(drop='first')
preprocessor=ColumnTransformer(
    [
     ('OneHotEncoder',categorical_transformer,cat_feature),
     ('StandardScaler',numerical_transformer,num_feature)
    ],remainder='passthrough'
)
label_encoder_columns=['model']

In [168]:
x=preprocessor.fit_transform(x)

In [169]:
print(pd.DataFrame(x))

        0    1    2    3    4    5    6         7         8          9   \
0      1.0  0.0  0.0  0.0  0.0  1.0  1.0 -1.519714  0.983562   1.247335
1      1.0  0.0  0.0  0.0  0.0  1.0  1.0 -0.225693 -0.343933  -0.690016
2      1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.536377  1.647309   0.084924
3      1.0  0.0  0.0  0.0  0.0  1.0  1.0 -1.519714  0.983562  -0.360667
4      0.0  0.0  1.0  0.0  0.0  0.0  1.0 -0.666211 -0.012060  -0.496281
...    ...  ...  ...  ...  ...  ...  ...       ...       ...        ...
15406  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.508844  0.983562  -0.869744
15407  0.0  0.0  0.0  0.0  0.0  1.0  1.0 -0.556082 -1.339555  -0.728763
15408  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.407551 -0.012060   0.220539
15409  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.426247 -0.343933  72.541850
15410  0.0  0.0  0.0  0.0  0.0  1.0  0.0 -1.024131 -1.339555  -0.825631

             10        11        12        13
0     -0.000276 -1.324259 -1.263352 -0.403022
1     -0.192071 -0.554718 -0.432571 -0.403022
2     -0.647583 -0.554718 -0.479113 -0.403022
3      0.292211 -0.936610 -0.779312 -0.403022
4      0.735736  0.022918 -0.046502 -0.403022
...         ...       ...       ...       ...
15406  0.026096 -0.767733 -0.757204 -0.403022
15407 -0.527711 -0.216964 -0.220803  2.073444
15408  0.344954  0.022918  0.068225 -0.403022
15409 -0.887326  1.329794  0.917158  2.073444
15410 -0.407839  0.020999  0.395884 -0.403022

[15411 rows x 14 columns]

# **Train and Test splits the models**

As you can see, the `original_car_name` column now represents the car names in a single column again. You can apply a similar process to other one-hot encoded features if needed.

In [170]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((12328, 14), (3083, 14))

# **Model Traning and Model Selection**

In [171]:
#Create a function to Evalute the model
def evaluate_model(true,predicted):
  mae=mean_absolute_error(true,predicted)
  mse=mean_squared_error(true,predicted)
  rmse=np.sqrt(mean_squared_error(true,predicted))
  r2=r2_score(true,predicted)
  return mae,mse,rmse,r2

In [172]:
#Begining model traning
import numpy as np
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor,ExtraTreesRegressor,BaggingRegressor
from sklearn.svm import SVR

#Create a function to Evalute the model
def evaluate_model(true,predicted):
  mae=mean_absolute_error(true,predicted)
  mse=mean_squared_error(true,predicted)
  rmse=np.sqrt(mean_squared_error(true,predicted))
  r2=r2_score(true,predicted)
  return mae,mse,rmse,r2

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'KNeighborsRegressor':KNeighborsRegressor(),
    'DecisionTreeRegressor':DecisionTreeRegressor(),
    'RandomForestRegressor':RandomForestRegressor(),
    'GradientBoostingRegressor':GradientBoostingRegressor(),
    'AdaBoostRegressor':AdaBoostRegressor(),
    'ExtraTreesRegressor':ExtraTreesRegressor(),
    'BaggingRegressor':BaggingRegressor(),
    'SVR':SVR()
}
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(x_train,y_train)
  y_train_pred=model.predict(x_train)
  y_test_pred=model.predict(x_test)
  model_train_mae,model_train_mse,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
  model_test_mae,model_test_mse,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
  print(list(models.keys())[i])
  print('Model performance for Training set')
  print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
  print("- Mean Squared Error: {:.4f}".format(model_train_mse))
  print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
  print("- R2 Score: {:.4f}".format(model_train_r2))
  print('----------------------------------')
  print('Model performance for Test set')
  print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print("- Mean Squared Error: {:.4f}".format(model_test_mse))
  print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
  print("- R2 Score: {:.4f}".format(model_test_r2))
  print('='*35)
  print('\n')

LinearRegression
Model performance for Training set
- Root Mean Squared Error: 553855.6665
- Mean Squared Error: 306756099359.7596
- Mean Absolute Error: 268101.6071
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502543.5930
- Mean Squared Error: 252550062888.5655
- Mean Absolute Error: 279618.5794
- R2 Score: 0.6645
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 553855.6710
- Mean Squared Error: 306756104248.3742
- Mean Absolute Error: 268099.2226
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502542.6696
- Mean Squared Error: 252549134806.7814
- Mean Absolute Error: 279614.7461
- R2 Score: 0.6645
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 553856.3160
- Mean Squared Error: 306756818740.9265
- Mean Absolute Error: 268059.8015
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502533.8230
- Mean Squared Error: 252540243247.9686
- Mean Absolute Error: 279557.2169
- R2 Score: 0.6645
===================================


KNeighborsRegressor
Model performance for Training set
- Root Mean Squared Error: 325885.9831
- Mean Squared Error: 106201673981.1810
- Mean Absolute Error: 91430.9701
- R2 Score: 0.8691
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 253071.9428
- Mean Squared Error: 64045408211.3607
- Mean Absolute Error: 112672.8917
- R2 Score: 0.9149
===================================


DecisionTreeRegressor
Model performance for Training set
- Root Mean Squared Error: 20797.2352
- Mean Squared Error: 432524990.5364
- Mean Absolute Error: 5164.8199
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 299842.3941
- Mean Squared Error: 89905461300.9740
- Mean Absolute Error: 123952.3381
- R2 Score: 0.8806
===================================


RandomForestRegressor
Model performance for Training set
- Root Mean Squared Error: 139796.3289
- Mean Squared Error: 19543013561.4089
- Mean Absolute Error: 39706.8015
- R2 Score: 0.9759
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 228679.5052
- Mean Squared Error: 52294316113.1424
- Mean Absolute Error: 101509.7977
- R2 Score: 0.9305
===================================


GradientBoostingRegressor
Model performance for Training set
- Root Mean Squared Error: 204944.5104
- Mean Squared Error: 42002252335.7090
- Mean Absolute Error: 111709.5558
- R2 Score: 0.9482
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 259530.2112
- Mean Squared Error: 67355930549.1946
- Mean Absolute Error: 126829.9830
- R2 Score: 0.9105
===================================


AdaBoostRegressor
Model performance for Training set
- Root Mean Squared Error: 456451.8253
- Mean Squared Error: 208348268861.0709
- Mean Absolute Error: 336991.9959
- R2 Score: 0.7431
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 483570.7314
- Mean Squared Error: 233840652307.1150
- Mean Absolute Error: 355362.6431
- R2 Score: 0.6894
===================================


ExtraTreesRegressor
Model performance for Training set
- Root Mean Squared Error: 20816.8858
- Mean Squared Error: 433342735.6113
- Mean Absolute Error: 5231.1767
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 230783.5235
- Mean Squared Error: 53261034732.9656
- Mean Absolute Error: 103593.7883
- R2 Score: 0.9292
===================================


BaggingRegressor
Model performance for Training set
- Root Mean Squared Error: 122853.1570
- Mean Squared Error: 15092898187.4047
- Mean Absolute Error: 43467.1771
- R2 Score: 0.9814
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 237117.7613
- Mean Squared Error: 56224832713.3330
- Mean Absolute Error: 106475.6807
- R2 Score: 0.9253
===================================


SVR
Model performance for Training set
- Root Mean Squared Error: 924927.4320
- Mean Squared Error: 855490754407.4027
- Mean Absolute Error: 396078.7460
- R2 Score: -0.0548
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 896356.4311
- Mean Squared Error: 803454851626.8837
- Mean Absolute Error: 417315.5337
- R2 Score: -0.0673
===================================

# *By Using Hyperperameter tuning*

In [173]:
#Initialize few parameter for hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [174]:
knn_param={
    'n_neighbors':np.arange(1,30),
    'weights':['uniform','distance'],
    'algorithm':['auto','ball_tree','kd_tree','brute']
}

rf_param={
    'n_estimators':[100,200,500,1000],
    'max_depth':[3,5,10,20],
    'min_samples_split':[2,5,10,15],
    'min_samples_leaf':[1,2,5,10]
}

In [175]:
#Model list for hyperparamaeter tuning
randomcv_model={
    'KNeighborsRegressor':KNeighborsRegressor(),
    'RandomForestRegressor':RandomForestRegressor(),
}

In [177]:
model_param={}

for name,model,param in zip(randomcv_model.keys(),randomcv_model.values(),[knn_param,rf_param]):
  random=RandomizedSearchCV(estimator=model,param_distributions=param,n_iter=100,cv=5,verbose=2,n_jobs=-1,random_state=42)
  random.fit(x_train,y_train)
  model_param[name]=random.best_params_

  for model_name in model_param:
    print(f"{model_name} best params: {model_param[model_name]}")
    print('='*35)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

KeyboardInterrupt:

In [ ]:
#Retraning the models with best parameters
models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'KNeighborsRegressor':KNeighborsRegressor(algorithm='auto',n_neighbors=27,weights='distance'),
    'DecisionTreeRegressor':DecisionTreeRegressor(),
    'RandomForestRegressor':RandomForestRegressor(max_depth=20,min_samples_leaf=1,min_samples_split=10,n_estimators=1000),
    'GradientBoostingRegressor':GradientBoostingRegressor(),
    'AdaBoostRegressor':AdaBoostRegressor(),
    'ExtraTreesRegressor':ExtraTreesRegressor(),
    'BaggingRegressor':BaggingRegressor(),
    'SVR':SVR()
}

In [152]:
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(x_train,y_train)
  y_train_pred=model.predict(x_train)
  y_test_pred=model.predict(x_test)
  model_train_mae,model_train_mse,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
  model_test_mae,model_test_mse,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
  print(list(models.keys())[i])
  print('Model performance for Training set')
  print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
  print("- Mean Squared Error: {:.4f}".format(model_train_mse))
  print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
  print("- R2 Score: {:.4f}".format(model_train_r2))
  print('----------------------------------')
  print('Model performance for Test set')
  print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print("- Mean Squared Error: {:.4f}".format(model_test_mse))
  print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
  print("- R2 Score: {:.4f}".format(model_test_r2))
  print('='*35)
  print('\n')

KNeighborsRegressor
Model performance for Training set
- Root Mean Squared Error: 325885.9831
- Mean Squared Error: 106201673981.1810
- Mean Absolute Error: 91430.9701
- R2 Score: 0.8691
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 253071.9428
- Mean Squared Error: 64045408211.3607
- Mean Absolute Error: 112672.8917
- R2 Score: 0.9149
===================================


RandomForestRegressor
Model performance for Training set
- Root Mean Squared Error: 143430.9461
- Mean Squared Error: 20572436304.6652
- Mean Absolute Error: 39829.6304
- R2 Score: 0.9746
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 228464.4519
- Mean Squared Error: 52196005787.1898
- Mean Absolute Error: 101469.6171
- R2 Score: 0.9307
===================================